export const SET_DISPLAYINFOS = "SET_DISPLAYINFOS"
export const SET_LOADING = "SET_LOADING"
export const SET_ERROR ="SET_ERROR"
export const SET_CANVASHASH ='SET_CANVASHASH'
export const SET_FINGERPRINTDATA = "SET_FINGERPRINTDATA"
export const SET_IPINFOS = "SET_IPINFOS"