export const SET_DISPLAYINFOS = "SET_DISPLAYINFOS"
export const SET_LOADING = "SET_LOADING"
export const SET_ERROR ="SET_ERROR"
export const SET_CANVASHASH ='SET_CANVASHASH'
export const SET_FINGERPRINTDATA = "SET_FINGERPRINTDATA"
export const SET_IPINFOS = "SET_IPINFOS"

export const SET_FINGERPRINT ="SET_FINGERPRINT"
export const SET_LASTVISITS ="SET_LASTVISITS"

export const SET_LASTVISITSTEXT ="SET_LASTVISITSTEXT"

export const RESET_STORE = 'RESET_STORE'
export const SET_DRAWVARIABLES = "SET_DRAWVARIABLES"
export const SET_POINTER = 'SET_POINTER'
export const  SET_TIMETOCLICKBUTTON = "SET_TIMETOCLICKBUTTON"

